name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - docs # Change this to the branch where your documentation resides
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dist.txt

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Local pip install
        run: |
          pip install .

      - name: Install dependencies 2
        run: |
          pip install sphinx sphinx-rtd-theme  # Add any other dependencies needed

      - name: Build the documentation
        run: |
          cd docs
          make html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/build/html"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
